# Generated by Django 4.2.1 on 2023-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0003_alter_producto_descripcion_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
