# Generated by Django 4.2.1 on 2023-06-13 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicPro', '0005_producto_cantidad_alter_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('codigo_seguimiento', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo de Seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pedido')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizada')),
                ('estado', models.CharField(choices=[('En preparacion', 'En preparacion'), ('En camino', 'En camino'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido')),
                ('direccion_envio', models.CharField(blank=True, max_length=70, verbose_name='Direccion del pedido')),
                ('metodo_pago', models.CharField(blank=True, choices=[('Debito', 'Debito'), ('Credito', 'Credito'), ('Transferencia', 'Transferencia')], max_length=100, verbose_name='Metodo de Pago')),
                ('producto', models.ManyToManyField(blank=True, to='MusicPro.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
