# Generated by Django 4.2.1 on 2023-06-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0011_remove_transporte_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_pedido', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='MusicPro.producto')),
            ],
        ),
    ]
