# Generated by Django 4.2.1 on 2023-06-19 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0013_alter_ordendecompra_descripcion_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('orden_de_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicPro.ordendecompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicPro.producto')),
            ],
        ),
    ]
