# Generated by Django 4.2.1 on 2023-06-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0015_itemordencompra_ordencompra_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOrdenCompra',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
