# Generated by Django 4.2.1 on 2023-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0017_itemordencompra_ordencompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección del pedido'),
        ),
    ]
