# Generated by Django 4.2.1 on 2023-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0018_alter_transporte_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección del pedido'),
        ),
    ]
