# Generated by Django 4.2.1 on 2023-06-21 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicPro', '0019_ordencompra_direccion_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemordencompra',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'verbose_name_plural': 'ordenes'},
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
