# Generated by Django 4.2.1 on 2023-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0022_alter_direccionenvio_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionenvio',
            options={'verbose_name_plural': 'direcciones'},
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud_exitosa',
            field=models.BooleanField(default=False, verbose_name='Solicitud exitosa'),
        ),
    ]
