# Generated by Django 4.2.1 on 2023-06-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0023_alter_direccionenvio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
