# Generated by Django 4.2.1 on 2023-06-23 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicPro', '0024_ordencompra_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.IntegerField(default=0)),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=70, null=True, verbose_name='Código de seguimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
    ]
