# Generated by Django 4.2.1 on 2023-06-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0025_codigotransporte_delete_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
