# Generated by Django 4.2.1 on 2023-06-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0026_alter_direccionenvio_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
