# Generated by Django 4.2.1 on 2023-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0027_alter_direccionenvio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_instrumento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
